name       : openocd
version    : 0.10.0
release    : 2
source     :
    - https://versaweb.dl.sourceforge.net/project/openocd/openocd/0.10.0/openocd-0.10.0.tar.bz2 : 7312e7d680752ac088b8b8f2b5ba3ff0d30e0a78139531847be4b75c101316ae
license    : GPL-2.0
component  : programming.tools
summary    : Open On-Chip Debugger
description: |
    Free and Open On-Chip Debugging, In-System Programming and Boundary-Scan Testing
builddeps  :
    - pkgconfig(libftdi1)
    - pkgconfig(libusb-1.0)
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-5704.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 contrib/60-openocd.rules -t $installdir/%libdir%/udev/rules.d/
